blank_issues_enabled: true
contact_links:
  - name: Ask a question ‚ùì
    url: https://github.com/Rviewer-Challenges/skeleton-ts-react-webapp/discussions/new
    about: Ask a question or request support for using this skeleton
